#!/usr/bin/sh
if [ "$2" = up ]; then
	INET=$(/sbin/ip addr show dev "$1" | /bin/grep inet)
	qubesdb-write /qubes-netvm-external-ip "$INET"
	systemctl restart qubes-firewall
	/usr/lib/qubes/qubes-setup-dnat-to-ns
fi
if [ "$2" = down ]; then
	qubesdb-write /qubes-netvm-external-ip ""
fi
if [ "$2" = "dns-change" ]; then
	systemctl restart qubes-firewall
	/usr/lib/qubes/qubes-setup-dnat-to-ns
fi
